127.0.0.1 - - [14/Oct/2024 17:21:05] "POST /do_segmentation HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/j/J.Mercado/Flask-LISCA/app.py", line 106, in do_segmentation
    pyama_util.segment_positions(nd2_path, out_dir, positions, segmentation_channel, fluorescence_channels, frame_min=frame_min, frame_max=frame_max)
  File "/home/j/J.Mercado/Flask-LISCA/pyama_util.py", line 644, in segment_positions
    data_labels[index,:,:] = label_segmentation[:,:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/j/J.Mercado/Flask-LISCA/fsk_py/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 982, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 7] Can't write data (file write failed: time = Mon Oct 14 17:21:05 2024
, filename = '/project/ag-moonraedler/projects/FlowCellProject/PyamaSimonBackup/XY07/data.h5', file descriptor = 13, errno = 7, error message = 'Argument list too long', buf = 0x56476c26fce8, total write size = 8372224, bytes this sub-write = 8372224, bytes actually written = 18446744073709551615, offset = 0)